name: Flask Workflow
on: push
jobs:
  push-job:
    name: Push check
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;
      - name: Run server
        run: |
          python3 server.py > log.txt 2>&1 &
